export { default as healthRouter } from "./health.routers"
export { default as userRouter } from "./user.router"
export {default as productRouter} from "./product.router"
export {default as categoryRouter} from "./category.router"
export {default as fixedProductRouter} from "./fixedProduct.router"